version: '3'

services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yaswhanth
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_api
    volumes:
      - ./data:/var/lib/postgresql/data